### ISSUE TITLE
Blank includes being generated

### ISSUE THREAD

**Issue by DStaelens** [smaccm/phase2#1]
Note this is on the red team branch:

While building the project, it errors because blank includes are being generated in some header files.

[CC] callback_2000ms.o
In file included from /home/staelensd/phase2/camkes/apps/smaccmpilot/components/thread_period_2000ms/src/callback_2000ms.c:4:0:
/home/staelensd/phase2/camkes/apps/smaccmpilot/include/callback_2000ms.h:9:10: error: empty filename in #include
 #include <>
          ^

**Comment by jameysharp** [comment]
I've confirmed this bug and pushed changes to Ivory to detect this class of bug earlier in development. We haven't fixed this particular bug yet though; it's in our `tower-aadl` compiler and I'm not yet sure what we should do about it.

**Comment by leepike** [comment]
Should be fixed now in master.
